title: Jared  Douville Resume
author: Jared Douville
email: Jared@saddlebackenterprises.net
description: > # this means to ignore newlines until "baseurl:"
 Jared Douville
31 years old
Happily engaed to Shayna Saddleback
Father of a beautfifull baby girl named Derian
Cyber Securitiy student and infosec enthuiest 
Github is Awsome 
Machine learning is exiting to learn about
Bug bounty is my hobby and hopefully one day my job!



# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  jared319

show_excerpts: true # set to false to remove excerpts on the homepage
